POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "username":"two",
    "email":"two@gmail.com",
    "password":"two123"
}

###
POST http://localhost:3000/api/users/verifymail
Content-Type: application/json

{
    "token" : "$2a$10$74MFLcHW7dwYTKVpGI07puV.LtdH15smateuRokXWGxYjdMmH2NTO"
}


### 
POST http://localhost:3000/api/users/signin
Content-Type: application/json

{
    "email":"two@gmail.com",
    "password":"two123"
}
